# -*- coding: utf-8 -*-
"""Normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LAUpI2cHY-THrlSkMEIvFnK6fxp-YWu
"""

text="there wre once Three Little Pigs!They lived in a straw hut,a stick hut,and a brick hut."
normalized_text=text.lower()
normalized_text="".join([char for char in normalized_text if char.isalnum() or char.isspace()])
normalized_text="".join(normalized_text.split())
print("Origibal Text:",text)
print("Normalized text:",normalized_text)