# -*- coding: utf-8 -*-
"""QASystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwCbDdroowvJvnN9xq5tY0OYxPTlaQdH
"""

from transformers import pipeline

# 1. Initialize the QA pipeline
qa = pipeline(
    "question-answering",
    model="deepset/roberta-base-squad2",  # robust model for extractive QA
)

# 2. Provide a question and context
context = """
The Python programming language was created by Guido van Rossum and first released in 1991.
It is known for its simplicity, readability, and wide adoption in data science, web development, and automation.
The language is maintained by the Python Steering Council.
"""

question = "Who created Python and when was it first released?"

# 3. Get the answer
result = qa(question=question, context=context)

print(f"Answer: {result['answer']}")
print(f"Score: {result['score']:.4f}")