# -*- coding: utf-8 -*-
"""Stemming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csuszIdpyeUAFEN8kbgtPPQwRR0dUhp0
"""

import nltk
from nltk.stem import PorterStemmer,WordNetLemmatizer
nltk.download('punkt')
nltk.download('wordnet')
text="The cats were running and studying"
stemmer=PorterStemmer()
stemmer_words=[stemmer.stem(word=word) for word in text.split()]
print(stemmed_words)
lemmatizer=WordNetLemmatizer()
lemmatizer_words=[lemmatizer.lemmatize(word=word,pos='v') for word in text.split()]
print(lemmatized_words)

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))
import re
text=input("enter any text:")
words=re.sub(r'[^\w\s]','',text).split()
filtered_words=[word for word in words if word.lower()not in stop_words]
print(filtered_words)