# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9DK3TisbPVj7fPFSJwC8i1kvhM6rCp5
"""

# Step 1: Install the sentence-transformers library
!pip install -U sentence-transformers

# Step 2: Import necessary functions
from sentence_transformers import SentenceTransformer, util

# Step 3: Load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 4: Input two sentences
sentence1 = "I like watching cartoons."
sentence2 = "I enjoy animated shows."

# Step 5: Convert sentences to embeddings
embedding1 = model.encode(sentence1, convert_to_tensor=True)
embedding2 = model.encode(sentence2, convert_to_tensor=True)

# Step 6: Calculate cosine similarity
similarity_score = util.pytorch_cos_sim(embedding1, embedding2)

# Step 7: Print the similarity score
print(f"Similarity Score: {similarity_score.item():.2f}")