# -*- coding: utf-8 -*-
"""textblob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hI1BeXg7q2Mit5p2HNCJ3NnBsH8mbWiZ
"""

import nltk
from textblob import TextBlob
text="The quick brown fox jumps over the lazy dog"
blob=TextBlob(text)
for word,pos in blob.tags:
  print(word,pos)

!python -m textblob.download_corpora
import nltk
from textblob import TextBlob
text="The quick brown fox jumps over the lazy dog"
blob=TextBlob(text)
for word,pos in blob.tags:
  print(word,pos)