# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHCHlayRvkPhda5k7jSHFznVxzeLnGhT
"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
texts=[
    "I love deep learning",
    "RNNs are powerful for sequence data",
    "Tokenization is the first step"
]
tokenizer=Tokenizer()
tokenizer.fit_on_texts(texts)
sequences=tokenizer.texts_to_sequences(texts)
padding=pad_sequences(sequences,padding='post')
print("Words:\n",tokenizer)
print("word index:\n",tokenizer.word_index)
print("Word sequence:\n",sequences)
print("Padding sequence:\n",padding)